# Generated by Django 6.1.1 on 2026-10-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=100)),
                ('game_description', models.TextField()),
                ('game_rating', models.FloatField()),
                ('game_release', models.DateField()),
            ],
        ),
    ]
